version: 2.1
orbs:
  codecov: codecov/codecov@4

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install -r requirements_devs.txt
      - run:
          name: Run tests and collect coverage
          command: pytest --cov src
      - codecov/upload

workflow:
  version: 2.1
  build-test:
    jobs:
      - build