name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.11']
      fail-fast: false
      
    steps:
      - name: Check out
        uses: actions/checkout@v4
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Test with tox
        run: tox

      - name: Upload coverage reports to Codecov
        run: |
          os_name=$(echo "${{ matrix.os }}" | awk -F- '{print $1}')  # Extract the OS name
          # Map GitHub Actions OS names to Codecov OS names
          if [ "$os_name" = "windows" ]; then
            codecov_os="windows"
          elif [ "$os_name" = "macos" ]; then
            codecov_os="macos"
          else
            codecov_os="linux"
          fi
          curl -Os https://uploader.codecov.io/latest/$codecov_os/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}
