name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11']
      fail-fast: false

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions

      - name: Test with tox
        run: tox

      - name: Set OS specific variables
        id: vars
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            echo "::set-output name=codecov_os::windows"
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            echo "::set-output name=codecov_os::macos"
          else
            echo "::set-output name=codecov_os::linux"
          fi

      - name: Upload coverage reports to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/${{ steps.vars.outputs.codecov_os }}/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}
