name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.11']
      fail-fast: false
      
    steps:
      - name: Check out
        uses: actions/checkout@v4
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
          
      - name: Test with tox
        run: |
          tox
  
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: rompoggi/MCTS_ClassifierChain

      - name: Upload coverage reports to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/${{ matrix.os }}/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}

  # build:
  #   runs-on: macos-latest
  #   name: Test python API
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Install requirements
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt
  #       pip install -r requirements_dev.txt

  #   - name: Run tests and collect coverage
  #     run: pytest --cov .
  #   - name: Upload coverage reports to Codecov
  #     run: |
  #       curl -Os https://uploader.codecov.io/latest/macos/codecov
  #       chmod +x codecov
  #       ./codecov -t ${CODECOV_TOKEN}
